### ISSUE TITLE
JUnit38ClassRunner does not recognize AssumptionViolationException

### ISSUE THREAD

**Issue by maciejmikosik** [junit-team/junit#1100]
Running this class

```
@RunWith(AllTests.class)
public class AssumptionsInJunit3Test {
  public static junit.framework.Test suite() {
    TestSuite suite = new TestSuite("suite");
    suite.addTest(new TestCase("internal_assumption") {
      protected void runTest() throws Throwable {
        throw new org.junit.internal.AssumptionViolatedException("");
      }
    });
    suite.addTest(new TestCase("assumption") {
      protected void runTest() throws Throwable {
        throw new org.junit.AssumptionViolatedException("");
      }
    });
    return suite;
  }
}
```

with eclipse junit runner reports both tests as failed instead of ignored.
Stack trace shows that `org.junit.internal.runners.JUnit38ClassRunner` was used.

```
org.junit.internal.AssumptionViolatedException: 
	at AssumptionsInJunit3Test$1.runTest(AssumptionsInJunit3Test.java:13)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

Is this an expected behavior or something that can be fixed?

**Comment by kcooney** [comment]
Assume is for JUnit4-style tests, but junit.framework.TestCase is used to define a JUnit3-style test. Any reason why you cannot rewrite tge test in JUnit4-style?

**Comment by maciejmikosik** [comment]
I'm working on a project that generates tests programatically at runtime.
I'm not sure, but I think this is impossible with Junit 4 model or at least is not as straightforward.
You can take a look at what I'm trying to accomplish here https://github.com/quackery/quackery

**Comment by kcooney** [comment]
The Runner abstraction should make this easy in JUnit4. If that doesn't help, I suggest the mailing list or Stackoverflow.
