### ISSUE TITLE
test spring4 restful controller with junit 4.12 question

### ISSUE THREAD

**Issue by liangzai-cool** [junit-team/junit#1198]
**my controller is:**
```java
package org.xueliang.web.blog.admin.controller.api.system;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.xueliang.web.blog.admin.controller.result.Result;
import org.xueliang.web.blog.admin.service.system.ConfigService;

@RestController
@RequestMapping("/api/system/config/")
public class ConfigController {
	
	@Autowired
	private ConfigService configService;
	
	@RequestMapping(value = "")
	public Result getConfigMap(){
		return configService.getConfigMap();
	}
}

```

**my junit test class is:**
```java
package org.xueliang.web.blog.admin.controller.api.system;

import net.sf.json.JSONObject;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;
import org.junit.Test;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.xueliang.web.blog.admin.controller.api.BaseApiTest;
import org.xueliang.web.blog.admin.model.user.User;

public class ConfigControllerTest extends BaseApiTest {

	@Test
	public void getConfigTest() throws Exception{
		MockHttpServletRequestBuilder mockHttpServletRequestBuilder = MockMvcRequestBuilders
				.post("/api/system/config/").servletPath("/api/system/config")
				.sessionAttr("user", new User());
		MvcResult mvcResult = mockMvc.perform(mockHttpServletRequestBuilder).andReturn();
		
		MockHttpServletResponse response = mvcResult.getResponse();
		int status = response.getStatus();
		String responseStr = response.getContentAsString();
		
		Assert.assertThat(status, CoreMatchers.equalTo(200));
		Assert.assertThat(responseStr, CoreMatchers.notNullValue());
		Assert.assertThat("", CoreMatchers.not(CoreMatchers.equalTo(responseStr.trim())));
		Assert.assertThat("0", CoreMatchers.equalTo(JSONObject.fromObject(responseStr).optString("code")));
	}
}

```

**and the BaseApiTest class is:**
```java
package org.xueliang.web.blog.admin.controller.api;

import org.junit.Before;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.ContextHierarchy;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

/**
 * 接口功能集成测试
 * @author Liang
 *
 */
@RunWith(SpringJUnit4ClassRunner.class)
@WebAppConfiguration(value = "WebContent")
@ContextHierarchy({
		@ContextConfiguration(name = "parent", locations = "classpath:springMVC-servlet.xml"),
		@ContextConfiguration(name = "child", locations = "classpath:springMVC-servlet.xml") })
public class BaseApiTest {

	@Autowired
	protected WebApplicationContext context;
	protected MockMvc mockMvc;
	
	@Before
	public void setUp() {
		mockMvc = MockMvcBuilders.webAppContextSetup(context).build();
	}
}

```
**the ConfigController class can response right when i use browse with `http://localhost:8080/liang.blog.admin/api/system/config/`
and it response content is : **
```json
{

    "code": 0,
    "msg": 

{

    "configMap": 

        {
            "staticUrl": "http://xxx.xx.xxx.xxx/staticdn/static3.9/",
            "key2": "value2",
            "key1": "value1"
        }
    }

}
```

**but junit say:**
```
java.lang.AssertionError: 
Expected: not ""
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.xueliang.web.blog.admin.controller.api.system.ConfigControllerTest.getConfigTest(ConfigControllerTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**but when I change the value of @requestmapping in ConfigController to a str, and change the post url and servlet url in  ConfigControllerTest class to right,it run right.**

**can you tell me how to test controller when the `@RequestMapping(value = "")`?**
**thank you!**

**Comment by kcooney** [comment]
The issue tracker is for issues with the JUnit framework

For questions about testing your own code, you can post to the maing list or use StackOverflow.
