### ISSUE TITLE
Adding new test causing assertion failures in existing tests

### ISSUE THREAD

**Issue by hodge1024** [junit-team/junit#1260]
I'm attempting to add a new test class to an existing test project.  I'm running Junit 4.11 within eclipse environment working on an eclipse plugin project.

Adding a new test class seems to work fine and existing tests work as expected, however when I add a test method (annotated with @Test annotation) then existing tests fail with assertion errors.  The newly added test has no body and doesn't do anything, just adding the annotation is sufficient to cause the failure.

I'm at the point where I can't add new tests due to this issue.  Also attempted to add tests in a sub package and got the same result.

Stack trace for the failing test follows: -

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at [CLIENT NAME HERE].info.recordings.data.SignaldataPointerLocaliserTest.runAndAssertLocalisationResult(SignaldataPointerLocaliserTest.java:197)
	at [CLIENT NAME HERE].info.recordings.data.SignaldataPointerLocaliserTest.valueInRpmStaysInRpmAfterLocalisation(SignaldataPointerLocaliserTest.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:62)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:23)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:56)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by marcphilipp** [comment]
Are you executing the new test as a Plugin test or a regular JUnit test?

**Comment by hodge1024** [comment]
I'm running as a Plugin test, as the project we're working on is a plugin.

**Comment by marcphilipp** [comment]
Without the actual code it's impossible to see what's causing the test to fail. Can you post a simplified version of the test class that fails?

**Comment by hodge1024** [comment]
I'll discuss with client, depends on their copyright rules for the code in question.  Will get back to you.

**Comment by kcooney** [comment]
My guess is there is some kind of static state in the code being tested or in the test itself, so the tests aren't isolated. Adding the test changes the test order. In any case, your best coarse of action is to use the debugger to see why the tests are failing.

**Comment by hodge1024** [comment]
Looking at the code there is some static initialization going on (in the code under test).  I'm stepping through to see specifically where the null value return gets introduced.  If successful will try to produce a generic test that simulates the issue.   Can't post production code here.

**Comment by hodge1024** [comment]
OK, got to the bottom of this.  Seems our existing tests were dependent on ordering of test execution.  Adding additional tests changed order of execution and caused a couple of failures.   Added additional mocking to ensure state was correctly setup and now working regardless of order.  Thanks for your help.

**Comment by hodge1024** [comment]
Closing issue.

**Comment by marcphilipp** [comment]
Thanks for reporting back! Glad you were able to figure out the cause of the problem.
